server:
  port: 8000
  
  

spring:
  application:
    name: NJ-EMPLOYEES-CLOUD-CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mapoulo/NJ_Employees_ConfigServer
          clone-on-start: true      
